language: node_js
node_js:
  - "8"
  - "10"
sudo: false
cache:
  yarn: true
  directories:
  - "node_modules"
install:
  - yarn
script:
  - yarn lint
  - yarn test:coverage
after_success:
  - yarn coverage:send
